version: '3'
services:
  app:
    image: image-smkp-upy:1.0
    container_name: smkp_upy_app
    build: .
    ports: 
      - 3000:3000 
    restart: on-failure
    volumes:
      - volsmkp:/usr/src/app/    
    networks:
      - smkp_network


  database:
    image: mysql:5.7
    container_name: smkp_upy_db
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=database 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=root
    command: --sql_mode=""
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - smkp_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smkp_upy_phpmyadmin
    depends_on:
      - database
    environment:
      - PMA_HOST=database # Note the "mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASS}
    ports:
      - 9090:80
    restart: always
    networks:
      - smkp_network

volumes:
  volsmkp:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  smkp_network:
    driver: bridge