version: '3'
services:
  app:
    container_name: smkp_upy_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-mysql          
    networks:
      - fullstack


  fullstack-mysql:
    image: mysql:5.7
    container_name: smkp_upy_db
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DC_DB_HOST} 
      - MYSQL_USER=${DC_DB_USER}
      - MYSQL_PASSWORD=${DC_DB_PASSWORD}
      - MYSQL_DATABASE=${DC_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DC_DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smkp_upy_phpmyadmin
    depends_on:
      - fullstack-mysql
    environment:
      - PMA_HOST=fullstack-mysql # Note the "fullstack-mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=${DC_DB_USER}
      - PMA_PORT=${DC_DB_PORT}
      - PMA_PASSWORD=${DC_DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - fullstack


volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge